USE ClientesGFT
GO
INSERT INTO Status_Fluxo(Id,Descricao)
VALUES 
		(1,'EM_CADASTRO'),
		(2,'AGUARDANDO_GERENCIA'),
		(3,'AGUARDANDO_CONTROLE_DE_RISCO'),
		(4,'APROVADO'),
		(5,'REPROVADO'),
		(6,'CORRECAO_PERFIL');