/*CREATE DATABASE ClientesGFT;*/

BEGIN TRAN;
USE ClientesGFT;

DROP TABLE IF EXISTS Fluxo_Aprovacao;

DROP TABLE IF EXISTS Clientes_Telefones;
DROP TABLE IF EXISTS Clientes;

DROP TABLE IF EXISTS Status_Fluxo;

DROP TABLE IF EXISTS Usuario_Perfil;
DROP TABLE IF EXISTS Perfils;

DROP TABLE IF EXISTS Enderecos;
DROP TABLE IF EXISTS Ceps;
DROP TABLE IF EXISTS Cidades;
DROP TABLE IF EXISTS Estados;
DROP TABLE IF EXISTS Paises;

DROP TABLE IF EXISTS Usuarios;


/* ----- UTILITÁRIOS ----- */

CREATE TABLE Status_Fluxo(
	Id INTEGER PRIMARY KEY,
	Descricao VARCHAR(50)
)



/* ----- CEP -----*/

CREATE TABLE Paises(
	Id INTEGER PRIMARY KEY,
	Pais VARCHAR(60) UNIQUE NOT NULL,
	Sigla VARCHAR(2) UNIQUE NOT NULL
)

CREATE TABLE Estados(
	Id INTEGER PRIMARY KEY,
	Estado VARCHAR(50) UNIQUE NOT NULL,
	IdPais INTEGER NOT NULL,

	CONSTRAINT FK__ESTADOS__PAIS FOREIGN KEY (IdPais)
	REFERENCES Paises(Id)
)

CREATE TABLE Cidades(
	Id INTEGER PRIMARY KEY,
	Cidade VARCHAR(50) UNIQUE NOT NULL,
	IdEstado INTEGER NOT NULL,

	CONSTRAINT FK__CIDADES__ESTADO FOREIGN KEY(IdEstado)
	REFERENCES Estados(Id)
)

CREATE TABLE Enderecos(
	Id INTEGER PRIMARY KEY IDENTITY(1,1),
	IdCidade INTEGER,
	Cep VARCHAR(8),
	Rua VARCHAR(255) NOT NULL,
	Bairro VARCHAR(255) NOT NULL,
	Numero INTEGER,
	Complemento VARCHAR(255),

	CONSTRAINT FK__ENDERECOS__CIDADE FOREIGN KEY(IdCidade)
	REFERENCES Cidades(Id)
)



/* ----- USUARIOS ----- */

CREATE TABLE Perfils(
	Id INTEGER PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(20) NOT NULL,
	Ativo BIT DEFAULT 1
)

CREATE TABLE Usuarios(
	Id INTEGER PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(255) NOT NULL,
	Login VARCHAR(255) UNIQUE NOT NULL,
	Senha VARCHAR(255) NOT NULL,
	Ativo BIT DEFAULT 1,
	DataCadastro DATETIME DEFAULT GETDATE()
)

CREATE TABLE Usuario_Perfil(
	IdUsuario INTEGER,
	IdPerfil INTEGER,

	CONSTRAINT PK__USUARIO_PERFIL PRIMARY KEY(IdUsuario, IdPerfil),
	CONSTRAINT FK__USUARIO_PERFIL__USUARIO FOREIGN KEY(IdUsuario)
	REFERENCES Usuarios(Id),
	CONSTRAINT FK__USUARIO_PERFIL__PERFIL FOREIGN KEY(IdPerfil)
	REFERENCES Perfils(Id)
)



/* ----- CLIENTES ----- */

CREATE TABLE Clientes(
	Id INTEGER PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(255) NOT NULL,
	CPF VARCHAR(11) UNIQUE,
	RG VARCHAR(9),
	DataNasc DATETIME NOT NULL,
	Email VARCHAR(255) NOT NULL,
	IdStatusAtual INTEGER,

	IdEndereco INTEGER,

	DataCadastro DATETIME DEFAULT GETDATE(),
	DataAlteracao DATETIME DEFAULT GETDATE()

	CONSTRAINT FK__CLIENTES__STATUS_FLUXO FOREIGN KEY(IdStatusAtual)
	REFERENCES Status_Fluxo(Id),
	CONSTRAINT FK__CLIENTES__ENDERECO FOREIGN KEY(IdEndereco)
	REFERENCES Enderecos(Id)
)

CREATE TABLE Clientes_Telefones(
	Id INTEGER PRIMARY KEY IDENTITY(1,1),
	IdCliente INTEGER,
	Telefone VARCHAR(20) NOT NULL,

	CONSTRAINT FK__CLIENTES_TELEFONES__CLIENTE FOREIGN KEY(IdCliente)
	REFERENCES Clientes(Id)
)



/* ----- FLUXO DE APROVAÇÃO ----- */

CREATE TABLE Fluxo_Aprovacao(
	Id INTEGER PRIMARY KEY IDENTITY(1,1),
	IdUsuario INTEGER NOT NULL,
	IdCliente INTEGER NOT NULL,
	IdStatus INTEGER NOT NULL,
	DataCriacao DATETIME DEFAULT GETDATE(),

	CONSTRAINT FK__FLUXO_APROVACAO__USUARIO FOREIGN KEY(IdUsuario)
	REFERENCES Usuarios(Id),
	CONSTRAINT FK__FLUXO_APROVACAO__CLIENTE FOREIGN KEY(IdCliente)
	REFERENCES Clientes(Id),
	CONSTRAINT FK__FLUXO_APROVACAO__STATUS_ANTERIOR__STATUS_FLUXO FOREIGN KEY(IdStatus)
	REFERENCES Status_Fluxo(Id)
)

COMMIT TRAN;